services:
  bethepet_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge