services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - bethepet_api
    networks:
      - app_network

  bethepet_api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:  
      - "8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_network

  chatbot:
    build: ./chatbot
    ports:
      - "8001:8001"
    volumes:
      - ./chatbot/src:/app/src
      - ./api:/app/api
    depends_on:
      - bethepet_api
    networks:
      - app_network
    env_file:
      - .env.chatbot

networks:
  app_network:
    driver: bridge 