[tool.poetry]
name = "bethepet"
version = "0.1.0"
description = "A FastAPI service for pet health management"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.141.1"
uvicorn = "^0.54.0"
python-dotenv = "^1.0.1"
sqlalchemy = ">=2.0.29,<2.1"
psycopg2-binary = "^2.9.9"
pyjwt = "^2.15.0"
passlib = "1.7.4"
bcrypt = "4.0.1"
pydantic = {extras = ["email"], version = "^2.11.4"}
alembic = "^1.15.2"
pydantic-settings = "^2.0"
requests = "^2.31.0"
boto3 = "^1.38.32"
python-multipart = "^0.0.32"
pillow = "^12.3.0"
pandas = "^2.3.0"
openai = "^1.85.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
pytest-asyncio = "^1.4.0"
pytest-mock = "^3.12.0"

