"""add profile_image_url to dog table

Revision ID: 03452e1d885a
Revises: 496fbe23b5be
Create Date: 2025-06-09 09:23:00.919926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03452e1d885a'
down_revision: Union[str, None] = '496fbe23b5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogs', 'profile_image_url')
    # ### end Alembic commands ###
