"""Fix: Add HealthStatus enum

Revision ID: 40a8e5458bc8
Revises: 737820792483
Create Date: 2025-05-23 13:34:41.218839

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40a8e5458bc8"
down_revision: Union[str, None] = "737820792483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    health_status_enum = sa.Enum("normal", "warning", "abnormal", name="healthstatus")
    health_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "health_checks",
        sa.Column(
            "status",
            sa.Enum("normal", "warning", "abnormal", name="healthstatus"),
            nullable=False,
        ),
    )
    op.drop_column("health_checks", "is_normal")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "health_checks",
        sa.Column("is_normal", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("health_checks", "status")

    sa.Enum(name="healthstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
