"""Add numeric_value and unit to HealthCheck mode

Revision ID: 496fbe23b5be
Revises: 11b7a0d1e903
Create Date: 2025-06-07 17:24:30.365421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '496fbe23b5be'
down_revision: Union[str, None] = '11b7a0d1e903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_checks', sa.Column('numeric_value', sa.Float(), nullable=True))
    op.add_column('health_checks', sa.Column('unit', sa.String(length=10), nullable=True))
    op.alter_column('health_checks', 'status',
               existing_type=postgresql.ENUM('normal', 'warning', 'abnormal', name='healthstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('health_checks', 'status',
               existing_type=postgresql.ENUM('normal', 'warning', 'abnormal', name='healthstatus'),
               nullable=False)
    op.drop_column('health_checks', 'unit')
    op.drop_column('health_checks', 'numeric_value')
    # ### end Alembic commands ###
