"""Add emergency models and insert seed guides

Revision ID: e86378f4489e
Revises: 5069f9e43283
Create Date: 2025-05-25 05:34:21.761282

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.sql import column, table

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e86378f4489e"
down_revision: Union[str, None] = "5069f9e43283"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emergency_guides",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("symptoms", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("first_aid", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hospitals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column(
            "type",
            sa.Enum("REGULAR", "EMERGENCY", "SPECIALIST", name="hospital_type"),
            nullable=False,
        ),
        sa.Column("is_emergency", sa.Boolean(), nullable=True),
        sa.Column("hours", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column(
            "specialties",
            sa.ARRAY(
                sa.Enum(
                    "GENERAL",
                    "EMERGENCY",
                    "SURGERY",
                    "INTERNAL",
                    "DERMATOLOGY",
                    "OPHTHALMOLOGY",
                    "DENTISTRY",
                    "ICU",
                    "EXOTIC",
                    name="specialty_enum",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hospitals_id"), "hospitals", ["id"], unique=False)

    emergency_guides_table = table(
        "emergency_guides",
        column("id", sa.String),
        column("title", sa.String),
        column("severity", sa.String),
        column("symptoms", sa.ARRAY(sa.String)),
        column("first_aid", sa.ARRAY(sa.String)),
        column("notes", sa.String),
    )

    op.bulk_insert(
        emergency_guides_table,
        [
            {
                "id": "poisoning",
                "title": "중독",
                "severity": "high",
                "symptoms": ["구토", "설사", "과도한 침 흘림", "경련", "의식 저하"],
                "first_aid": [
                    "먹은 독성 물질을 확인하세요.",
                    "구토를 유도하지 마세요 (수의사의 지시가 없는 한).",
                    "활성탄을 가지고 있다면 수의사와 상담 후 투여하세요.",
                    "즉시 동물병원으로 이동하세요.",
                ],
                "notes": "중독 물질과 섭취 시간을 기록해두면 치료에 도움이 됩니다.",
            },
            {
                "id": "seizure",
                "title": "발작",
                "severity": "high",
                "symptoms": [
                    "몸의 경직",
                    "의식 상실",
                    "다리를 젓는 움직임",
                    "침 흘림",
                    "배변/배뇨 실수",
                ],
                "first_aid": [
                    "반려견의 주변에서 위험한 물건을 치우세요.",
                    "반려견을 만지거나 입에 손을 넣지 마세요.",
                    "발작 시간을 기록하세요.",
                    "발작이 1분 이상 지속되거나 연속으로 발생하면 즉시 병원으로 이동하세요.",
                ],
                "notes": "발작 전후 행동을 기록해두면 진단에 도움이 됩니다.",
            },
            {
                "id": "choking",
                "title": "질식",
                "severity": "high",
                "symptoms": [
                    "호흡 곤란",
                    "과도한 기침",
                    "입술이나 잇몸이 파랗게 변함",
                    "공황 상태",
                ],
                "first_aid": [
                    "반려견의 입을 열고 이물질이 보이면 조심스럽게 제거하세요.",
                    "하임리히 방법: 작은 개는 등을 위로 향하게 들고, 큰 개는 뒤에서 복부를 감싸고 위쪽으로 밀어올리세요.",
                    "이물질이 제거되지 않으면 즉시 병원으로 이동하세요.",
                ],
                "notes": "질식은 생명을 위협하는 응급 상황입니다. 신속하게 대처하세요.",
            },
            {
                "id": "heatstroke",
                "title": "열사병",
                "severity": "high",
                "symptoms": [
                    "과도한 헥헥거림",
                    "짙은 붉은색 잇몸",
                    "구토",
                    "설사",
                    "의식 저하",
                    "비틀거림",
                ],
                "first_aid": [
                    "시원한 장소로 이동시키세요.",
                    "미지근한 물로 몸을 적셔주세요 (차가운 물은 피하세요).",
                    "선풍기로 바람을 쐬어주세요.",
                    "물을 조금씩 마시게 하세요.",
                    "체온이 정상으로 돌아오더라도 반드시 병원에 방문하세요.",
                ],
                "notes": "여름철 차 안에 반려견을 절대 두지 마세요. 온도는 빠르게 상승합니다.",
            },
            {
                "id": "bleeding",
                "title": "출혈",
                "severity": "medium",
                "symptoms": [
                    "지속적인 출혈",
                    "혈액이 묻은 털",
                    "창백한 잇몸",
                    "약한 맥박",
                    "무기력",
                ],
                "first_aid": [
                    "깨끗한 천이나 거즈로 상처를 압박하세요.",
                    "출혈이 심하면 지혈대를 사용하세요 (최대 15분).",
                    "반려견을 따뜻하게 유지하고 움직임을 최소화하세요.",
                    "즉시 병원으로 이동하세요.",
                ],
                "notes": "출혈량이 많으면 쇼크 상태가 될 수 있으니 주의하세요.",
            },
            {
                "id": "fracture",
                "title": "골절",
                "severity": "medium",
                "symptoms": [
                    "다리를 절음",
                    "부기",
                    "비정상적인 각도",
                    "만졌을 때 통증",
                    "움직이지 않으려 함",
                ],
                "first_aid": [
                    "반려견을 진정시키고 움직임을 최소화하세요.",
                    "개방성 골절(뼈가 피부를 뚫고 나온 경우)은 깨끗한 천으로 덮으세요.",
                    "부목을 대지 마세요 (잘못하면 더 악화될 수 있습니다).",
                    "담요나 수건으로 조심스럽게 감싸서 병원으로 이동하세요.",
                ],
                "notes": "골절이 의심되면 반려견을 들어올릴 때 부상 부위를 지지해주세요.",
            },
            {
                "id": "dehydration",
                "title": "탈수",
                "severity": "medium",
                "symptoms": [
                    "피부 탄력성 저하",
                    "잇몸 건조",
                    "무기력",
                    "식욕 감소",
                    "소변량 감소",
                ],
                "first_aid": [
                    "깨끗한 물을 조금씩 자주 마시게 하세요.",
                    "전해질 용액을 제공하세요 (수의사와 상담 후).",
                    "시원하고 그늘진 곳에서 휴식을 취하게 하세요.",
                    "증상이 개선되지 않으면 병원에 방문하세요.",
                ],
                "notes": "탈수는 다른 질병의 증상일 수 있으니 원인을 파악하는 것이 중요합니다.",
            },
            {
                "id": "allergic",
                "title": "알레르기 반응",
                "severity": "medium",
                "symptoms": [
                    "얼굴 부종",
                    "두드러기",
                    "가려움",
                    "호흡 곤란",
                    "구토",
                    "설사",
                ],
                "first_aid": [
                    "알레르기 원인을 제거하세요.",
                    "수의사가 처방한 항히스타민제가 있다면 투여하세요.",
                    "호흡 곤란이나 심한 부종이 있으면 즉시 병원으로 이동하세요.",
                ],
                "notes": "이전에 알레르기 반응을 보인 적이 있다면, 수의사와 상담하여 응급 키트를 준비해두세요.",
            },
            {
                "id": "vomiting",
                "title": "구토와 설사",
                "severity": "low",
                "symptoms": [
                    "반복적인 구토",
                    "설사",
                    "식욕 감소",
                    "무기력",
                    "복부 통증",
                ],
                "first_aid": [
                    "물과 음식을 12시간 동안 제한하세요 (물은 소량씩 제공).",
                    "증상이 호전되면 삶은 닭고기와 흰쌀 같은 소화가 쉬운 음식을 소량 제공하세요.",
                    "24시간 이상 지속되거나 혈액이 섞여 있으면 병원에 방문하세요.",
                ],
                "notes": "구토물이나 대변의 상태(색상, 질감, 이물질 등)를 기록해두면 진단에 도움이 됩니다.",
            },
            {
                "id": "eyeinjury",
                "title": "눈 부상",
                "severity": "medium",
                "symptoms": [
                    "눈을 비비거나 긁음",
                    "충혈",
                    "부종",
                    "눈물 과다",
                    "눈을 감고 있음",
                ],
                "first_aid": [
                    "반려견이 눈을 더 긁지 않도록 방지하세요.",
                    "깨끗한 물로 눈을 부드럽게 씻어내세요.",
                    "이물질이 보이면 제거하려 하지 말고 병원에 방문하세요.",
                    "엘리자베스 칼라를 착용시키세요.",
                ],
                "notes": "눈 부상은 시력에 영향을 줄 수 있으므로 신속하게 치료해야 합니다.",
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hospitals_id"), table_name="hospitals")
    op.drop_table("hospitals")
    op.drop_table("emergency_guides")
